const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/quest/1', (req, res) => res.render('pages/promo/ar-quest1'))
  .get('/quest/2', (req, res) => res.render('pages/promo/ar-quest2'))
  .get('/quest/3', (req, res) => res.render('pages/promo/ar-quest3'))
  .get('/quest/4', (req, res) => res.render('pages/promo/ar-quest4'))
  .get('/quest/5', (req, res) => res.render('pages/promo/ar-quest5'))
  .get('/quest/6', (req, res) => res.render('pages/promo/ar-quest6'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
